create schema public;

comment on schema public is 'standard public schema';

alter schema public owner to postgres;

create table "user"
(
	id bigserial not null
		constraint table_name_pk
			primary key,
	email varchar not null,
	username varchar not null,
	password varchar not null,
	is_account_non_expired boolean,
	is_account_non_locked boolean,
	is_credentials_non_expired boolean,
	is_enabled boolean,
	role integer
);

alter table "user" owner to postgres;

create unique index table_name_email_uindex
	on "user" (email);

create unique index table_name_id_uindex
	on "user" (id);

create unique index table_name_username_uindex
	on "user" (username);

create table company
(
	id bigint generated by default as identity
		constraint company_pkey
			primary key,
	country varchar(255),
	currency varchar(255),
	description varchar(255),
	display_symbol varchar(255),
	exchange varchar(255),
	finnhub_industry varchar(255),
	ipo varchar(255),
	logo varchar(255),
	name varchar(255),
	ticker varchar(255),
	web_url varchar(255)
);

alter table company owner to postgres;

create table stock_data
(
	id bigint generated by default as identity (maxvalue 2147483647)
		constraint stock_data_pkey
			primary key,
	current_price double precision,
	high_price double precision,
	low_price double precision,
	open_price double precision,
	previous_close_price double precision
);

alter table stock_data owner to postgres;

create table user_company_tracking
(
	user_id bigint not null
		constraint fkj8xnhjbdxcoujqtytjtrb6f1r
			references "user",
	company_id bigint not null
		constraint fknigl8tiop33rh83jml9i8jf2u
			references company
);

alter table user_company_tracking owner to postgres;

create table company_metrics
(
	id bigint generated by default as identity (maxvalue 2147483647)
		constraint company_metrics_pkey
			primary key,
	half_year_daily_return double precision,
	quarter_year_daily_return double precision,
	"10_day_average_trading_volume" double precision,
	year_daily_return double precision,
	year_high double precision,
	year_high_date timestamp,
	year_low double precision,
	year_low_date timestamp
);

alter table company_metrics owner to postgres;

