create schema public;

comment on schema public is 'standard public schema';

alter schema public owner to postgres;

create table if not exists "user"
(
    id bigserial not null
        constraint table_name_pk
            primary key,
    email varchar not null,
    username varchar not null,
    password varchar not null,
    is_account_non_expired boolean,
    is_account_non_locked boolean,
    is_credentials_non_expired boolean,
    is_enabled boolean
);

alter table "user" owner to postgres;

create unique index if not exists table_name_email_uindex
    on "user" (email);

create unique index if not exists table_name_id_uindex
    on "user" (id);

create unique index if not exists table_name_username_uindex
    on "user" (username);

create table if not exists company
(
    id bigint generated by default as identity
        constraint company_pkey
            primary key,
    country varchar(255),
    currency varchar(255),
    description varchar(255),
    display_symbol varchar(255),
    exchange varchar(255),
    finnhub_industry varchar(255),
    ipo varchar(255),
    logo varchar(255),
    name varchar(255),
    ticker varchar(255),
    web_url varchar(255)
);

alter table company owner to postgres;

create table if not exists user_company_tracking
(
    user_id bigint not null
        constraint fkj8xnhjbdxcoujqtytjtrb6f1r
            references "user",
    company_id bigint not null
        constraint fknigl8tiop33rh83jml9i8jf2u
            references company
);

alter table user_company_tracking owner to postgres;

create table if not exists subscription
(
    id bigint not null
        constraint subscription_pk
            primary key,
    start_date date,
    end_date date,
    role integer not null,
    should_be_renew boolean not null,
    renew_level integer
);

alter table subscription owner to postgres;

create unique index if not exists subscription_id_uindex
    on subscription (id);

create table if not exists payment
(
    id varchar not null,
    user_id bigint not null
        constraint payment_user_id_fk
            references "user",
    subscription_level integer,
    is_completed boolean not null
);

alter table payment owner to postgres;
